config/routes.rb
Inventory::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  root :to => "inventories#index"
  get '/signin' => 'sessions#new'
  delete'/signout' => 'sessions#destroy'
  
  resources :inventories do
    collection do
      get :list
    end
  end
  
  #resources :sessions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/inventory_list.rb
class InventoryList < ActiveRecord::Base
  attr_accessible :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
=begin  
  helper_method :user_signed_in?, :current_user#, :is_admin?, :is_owner?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
  
  protected

  def user_signed_in?
    !session[:username].nil?
  end

  def current_user
    session[:username]
  end

  def login_required
    unless user_signed_in?
      redirect_to signin_path, notice: 'You need to be logged in before accessing this page'
    end
  end
=end

  def is_admin?
    unless session.has_key?(:is_admin)
      session[:is_admin] = Administrator.exists?(username: current_user)
    end
    session[:is_admin]
  end

  def is_owner?(device)
    current_user == device.owner
  end

  def admin_required
    unless is_admin?
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Only administrators can access this page' }
      end
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    #@users = User.all
    @inventories = InventoryList.all.collect(&:name)
    respond_to do |format|
      format.html # index.html.haml
    end
  end

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

  before_filter :login_required
  
  def index
    respond_to do |format|
      format.html # index.html.haml 
    end
  end
  
  def list
    @inventories = InventoryList.all.collect(&:name)
    respond_to do |format|
      format.html # list.html.haml 
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # GET /sign_in
  def new
  end

  # POST /sign_in
  def create
    if PramatiLdap::authenticate(params[:username], params[:password])
      session[:username] = params[:username]
      flash.now[:alert] = 'Successfully signed in'
      redirect_to list_inventories_path
    else
      flash.now[:error] = 'Invalid username and password'
      render action: :new
    end
  end

  # DELETE /sign_out
  def destroy
    session[:username], session[:is_admin] = nil, nil
    flash[:alert] = 'You\'re logged out of the application'
    redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
- if user_signed_in?
  .text-left
    %h3
      Inventory List
    %br
    %h4{:style => "color: #008080;"}
      Some text comes here
    %div
      - @inventories = ['Select Inventory'] + @inventories
      = select_tag(:inventory_name, options_for_select(@inventories), :style => 'width:142px;')
    %br
- else
  %h4{:style => "color: #008080;"}
    Description of the application comes here. 

app/views/inventories/index.html.haml
%h2
	"Inventory App"

app/views/inventories/list.html.haml
.text-left
  %h3
    Inventory List
  %br
  .hero-unit
    %h4{:style => "color: #008080;"}
      Some text comes here
    %div
      - @inventories = ['Select Inventory'] + @inventories
      = select_tag(:inventory_name, options_for_select(@inventories), :style => 'width:142px;')
    %br

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Inventory", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Inventory"
      %meta{:content => content_for?(:description) ? yield(:description) : "Inventory", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar
      .navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

-#    %title Inventory
-#    = stylesheet_link_tag    "application", :media => "all"
-#    = javascript_include_tag "application"
-#    = csrf_meta_tags
-#  %body
-#    .navbar
-#      .navbar-inner
-#        .container-fluid
-#          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
-#            %span.icon-bar
-#            %span.icon-bar
-#            %span.icon-bar
-#          %a.brand{:href => "/inventories/list"} Inventory
-#          .btn-group.pull-right
-#            %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
-#              %i.icon-user
-#              = user_signed_in? ? current_user : 'Guest'
-#              %span.caret
-#            %ul.dropdown-menu
-#              - if user_signed_in?
-#                %li= link_to("Sign Out", signout_path, :method => :delete)
-#              - else
-#                %li= link_to 'Sign In', signin_path
-#          .nav-collapse
-#            %ul.nav.pull-left
-#              %li= link_to 'Home', list_inventories_path
-#    .container
-#      .hero-unit
-#       = render 'shared/flashes'
-#      = yield
-#      %hr/
-#      %footer
-#        %p &copy; Copyright.Imaginea.2013.
-#    / /.container

app/views/shared/_flashes.html.haml
- flash.each do |name, msg|
  - unless msg.blank?
    - case name
      - when :alert, :error then
        = content_tag :div, msg, :class => "alert alert-error"
      - when :success then
        = content_tag :div, msg, :class => "alert alert-success"
      - when :warning then
        = content_tag :div, msg, :class => "alert alert-warning"
      - when :notice then
        = content_tag :div, msg, :class => "alert alert-info"
      - else 
        = content_tag :div, msg, :class => "alert alert-info"

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}